core/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('triangle.urls'))
]

triangle/urls.py
from django.urls import path

from . import views

app_name = 'triangle'
urlpatterns = [
    path('triangle/', views.triangle, name='triangle'),
    path('person/', views.person_list, name='person'),
    path('person/register', views.person_register, name='person_register'),
    path('person/<int:pk>/', views.person_update, name='person_update'),
]

triangle/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.email}'


class Logs(models.Model):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    DELETE = 'DELETE'
    METHOD_CHOICES = [
        (GET, 'GET'),
        (POST, 'POST'),
        (PUT, 'PUT'),
        (DELETE, 'DELETE'),
    ]

    path = models.CharField(max_length=255)
    method = models.CharField(max_length=6, choices=METHOD_CHOICES, default=GET)
    timestamp = models.DateTimeField(auto_now_add=True)
    get_data = models.JSONField(blank=True, null=True)
    post_data = models.JSONField(blank=True, null=True)

    def __str__(self):
        return f'{self.timestamp}, {self.method}'

    class Meta:
        verbose_name_plural = 'Logs'

triangle/forms.py
from django.core.validators import MinValueValidator
from django.forms import ModelForm, fields, forms

from .models import Person


class TriangleForm(forms.Form):
    leg1 = fields.FloatField(label="Leg 1", validators=[MinValueValidator(0.0000000000000000001)])
    leg2 = fields.FloatField(label='Leg 2', validators=[MinValueValidator(0.0000000000000000001)])


class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

triangle/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PersonForm, TriangleForm
from .models import Person


def triangle(request):
    hypotenuse = None
    if "Submit" in request.GET:
        user_form = TriangleForm(request.GET)

        if user_form.is_valid():
            leg1 = user_form.cleaned_data['leg1']
            leg2 = user_form.cleaned_data['leg2']
            hypotenuse = round((((leg1 ** 2) + (leg2 ** 2)) ** 0.5), 2)

            user_form = TriangleForm()
    else:
        user_form = TriangleForm()

    return render(request, 'triangle/triangle.html', {'form': user_form, 'hypotenuse': hypotenuse})


def person_list(request):
    users = Person.objects.all()
    return render(request, 'triangle/user_list.html', {'users': users})


def person_register(request):
    if request.method == 'POST':
        user_form = PersonForm(request.POST)

        if user_form.is_valid():
            user_form.save()
            return redirect('triangle:person')

    else:
        user_form = PersonForm()

    return render(request, 'triangle/user_register.html', {'form': user_form})


def person_update(request, pk):
    obj = get_object_or_404(Person, pk=pk)

    if request.method == 'POST':
        user_form = PersonForm(request.POST, instance=obj)

        if user_form.is_valid():
            obj = user_form.save()
            return redirect('triangle:person')

    else:
        user_form = PersonForm(instance=obj)

    return render(request, 'triangle/user_update.html', {'form': user_form, 'obj': obj})


def person_list(request):
    users = Person.objects.all()
    return render(request, 'triangle/user_list.html', {'users': users})


def person_register(request):
    if request.method == 'POST':
        user_form = PersonForm(request.POST)

        if user_form.is_valid():
            user_form.save()
            return redirect('triangle:person')

    else:
        user_form = PersonForm()

    return render(request, 'triangle/user_register.html', {'form': user_form})


def person_update(request, pk):
    obj = get_object_or_404(Person, pk=pk)

    if request.method == 'POST':
        user_form = PersonForm(request.POST, instance=obj)

        if user_form.is_valid():
            obj = user_form.save()
            return redirect('triangle:person')

    else:
        user_form = PersonForm(instance=obj)

    return render(request, 'triangle/user_update.html', {'form': user_form, 'obj': obj})

templates/triangle/codebase_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
</head>
<body>
    <h1>Update form for {{ obj }}</h1>
<form action="{% url 'triangle:first-model-update-form' pk=obj.pk %}" method="post">
    {% csrf_token %}
    {{ first_form.as_p }}

    <input type="submit" value="OK">
</form>

</body>
</html>

templates/triangle/get_forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get_Form</title>
</head>
<body>
<h1>Form for calculating the hypotenuse</h1>

<p><a href="{%  url 'index' %}">Home</a></p>


{% if calc %}
    <h2>The value of the hypotenuse {{ calc }}</h2>
{% endif %}

<form action="{% url 'triangle:get-form' %}" method="get">
    {{get_form.as_p}}
    <input type="submit" name="submit" value="OK">
</form>
</body>
</html>

templates/triangle/triangle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hypotenuse Calc</title>
</head>
<body>
    <h1>Calculator</h1>
    <form action="{% url 'triangle:triangle' %}" method="get">
        <p>{{ form.leg1.label_tag }} {{ form.leg1 }}</p>
        <p>{{ form.leg2.label_tag }} {{ form.leg2 }}</p>
    <input type="Submit" name="Submit" value="Calculate">
    </form>
    {% if hypotenuse %}
        <p>Hypotenuse: {{ hypotenuse }}</p>
    {% endif %}
</body>
</html>

templates/triangle/update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
</head>
<body>
    <h1>Update form for {{ obj }}</h1>
<form action="{% url 'triangle:first-model-update-form' pk=obj.pk %}" method="post">
    {% csrf_token %}
    {{ first_form.as_p }}

    <input type="submit" value="OK">
</form>

</body>
</html>

templates/triangle/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crudlist_New</title>
</head>
<body>
    <p>New crud List</p>
    <p><a href="{%  url 'index' %}">Home</a></p>
    <ul>
        {% for obj in objects %}
            <li> <a href="{% url 'triangle:first-model-update-form' pk=obj.pk %}">{{ obj }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>